name: 'PR Comment'
description: 'Post a comment on PR'
author: 'nhayashi'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'message-square'
  color: 'green'

# Define your inputs here.
inputs:
  repo-token:
    description: 'GITHUB_TOKEN secret'
    required: true
  message:
    description: 'Message to comment'
    required: true

# Define your outputs here.
outputs:
  comment-url:
    description: 'The PR comment URL'

runs:
  using: node20
  main: dist/index.js
